"""
NIST AI Risk Management Framework (AI RMF)

Based on NIST AI 100-1: Artificial Intelligence Risk Management Framework (AI RMF 1.0)
The primary US framework for AI risk management, widely adopted by US organizations.

Core Functions:
- GOVERN: Establish policies and procedures
- MAP: Understand context and risks
- MEASURE: Assess and monitor risks
- MANAGE: Implement controls and respond to risks
"""

from anchorscan.models import Requirement, Severity


NIST_AI_RMF_REQUIREMENTS = [
    # GOVERN Function
    Requirement(
        id="nist-001",
        name="Governance Policies & Procedures",
        description="Establish organizational policies, procedures, and accountability structures for AI risk management.",
        framework="NIST AI RMF",
        article="GOVERN-1",
        severity=Severity.CRITICAL,
        positive_patterns=[
            r"governance",
            r"Governance",
            r"policy",
            r"Policy",
            r"procedure",
            r"Procedure",
            r"accountability",
            r"Accountability",
            r"oversight",
            r"Oversight",
            r"board",
            r"committee",
            r"steering",
            r"charter",
            r"framework",
            r"Framework",
        ],
        negative_patterns=[],
    ),
    
    Requirement(
        id="nist-002",
        name="Risk Management Culture",
        description="Foster a culture of risk awareness and continuous improvement.",
        framework="NIST AI RMF",
        article="GOVERN-2",
        severity=Severity.HIGH,
        positive_patterns=[
            r"risk.?awareness",
            r"risk.?culture",
            r"continuous.?improvement",
            r"learning.?organization",
            r"training",
            r"education",
            r"awareness.?program",
            r"risk.?communication",
        ],
        negative_patterns=[],
    ),
    
    Requirement(
        id="nist-003",
        name="Documentation & Traceability",
        description="Maintain comprehensive documentation of AI system design, development, and deployment.",
        framework="NIST AI RMF",
        article="GOVERN-3",
        severity=Severity.CRITICAL,
        positive_patterns=[
            r"documentation",
            r"Documentation",
            r"traceability",
            r"Traceability",
            r"audit.?trail",
            r"version.?control",
            r"change.?log",
            r"design.?doc",
            r"requirements",
            r"specification",
            r"technical.?documentation",
        ],
        negative_patterns=[],
    ),
    
    # MAP Function
    Requirement(
        id="nist-004",
        name="Context Understanding",
        description="Understand the context in which the AI system operates, including use cases and stakeholders.",
        framework="NIST AI RMF",
        article="MAP-1",
        severity=Severity.HIGH,
        positive_patterns=[
            r"context",
            r"Context",
            r"use.?case",
            r"UseCase",
            r"stakeholder",
            r"Stakeholder",
            r"requirements",
            r"Requirements",
            r"scope",
            r"Scope",
            r"boundary",
            r"Boundary",
            r"operational.?context",
        ],
        negative_patterns=[],
    ),
    
    Requirement(
        id="nist-005",
        name="Risk Identification & Assessment",
        description="Identify and assess AI risks including accuracy, reliability, security, privacy, and fairness.",
        framework="NIST AI RMF",
        article="MAP-2",
        severity=Severity.CRITICAL,
        positive_patterns=[
            r"risk.?assessment",
            r"RiskAssessment",
            r"risk.?identification",
            r"threat.?modeling",
            r"vulnerability",
            r"Vulnerability",
            r"threat",
            r"Threat",
            r"risk.?analysis",
            r"risk.?register",
            r"risk.?matrix",
            r"accuracy",
            r"reliability",
            r"security",
            r"privacy",
            r"fairness",
            r"bias",
            r"Bias",
        ],
        negative_patterns=[],
    ),
    
    Requirement(
        id="nist-006",
        name="Data Quality & Management",
        description="Ensure data quality, provenance, and appropriate data management practices.",
        framework="NIST AI RMF",
        article="MAP-3",
        severity=Severity.CRITICAL,
        positive_patterns=[
            r"data.?quality",
            r"DataQuality",
            r"data.?provenance",
            r"data.?lineage",
            r"data.?governance",
            r"data.?management",
            r"data.?validation",
            r"data.?cleaning",
            r"data.?preprocessing",
            r"data.?integrity",
            r"data.?catalog",
        ],
        negative_patterns=[],
    ),
    
    # MEASURE Function
    Requirement(
        id="nist-007",
        name="Performance Testing & Evaluation",
        description="Conduct systematic testing and evaluation of AI system performance and behavior.",
        framework="NIST AI RMF",
        article="MEASURE-1",
        severity=Severity.CRITICAL,
        positive_patterns=[
            r"testing",
            r"Testing",
            r"evaluation",
            r"Evaluation",
            r"benchmark",
            r"Benchmark",
            r"test.?suite",
            r"test.?case",
            r"performance.?test",
            r"accuracy.?test",
            r"validation",
            r"Validation",
            r"verification",
            r"Verification",
            r"metrics",
            r"Metrics",
            r"evaluation.?metrics",
        ],
        negative_patterns=[],
    ),
    
    Requirement(
        id="nist-008",
        name="Bias & Fairness Assessment",
        description="Assess AI systems for bias, discrimination, and fairness across different groups.",
        framework="NIST AI RMF",
        article="MEASURE-2",
        severity=Severity.CRITICAL,
        positive_patterns=[
            r"bias",
            r"Bias",
            r"fairness",
            r"Fairness",
            r"discrimination",
            r"Discrimination",
            r"equity",
            r"Equity",
            r"disparate.?impact",
            r"equalized.?odds",
            r"demographic.?parity",
            r"fairness.?metric",
            r"bias.?detection",
            r"bias.?mitigation",
            r"protected.?attribute",
        ],
        negative_patterns=[],
    ),
    
    Requirement(
        id="nist-009",
        name="Security & Privacy Testing",
        description="Test AI systems for security vulnerabilities and privacy risks.",
        framework="NIST AI RMF",
        article="MEASURE-3",
        severity=Severity.CRITICAL,
        positive_patterns=[
            r"security.?test",
            r"SecurityTest",
            r"penetration.?test",
            r"pen.?test",
            r"vulnerability.?scan",
            r"adversarial.?test",
            r"adversarial.?attack",
            r"privacy.?test",
            r"privacy.?assessment",
            r"differential.?privacy",
            r"red.?team",
            r"redteam",
            r"security.?audit",
        ],
        negative_patterns=[],
    ),
    
    Requirement(
        id="nist-010",
        name="Monitoring & Observability",
        description="Implement continuous monitoring and observability for AI system behavior and performance.",
        framework="NIST AI RMF",
        article="MEASURE-4",
        severity=Severity.HIGH,
        positive_patterns=[
            r"monitoring",
            r"Monitoring",
            r"observability",
            r"Observability",
            r"telemetry",
            r"Telemetry",
            r"metrics",
            r"Metrics",
            r"logging",
            r"Logging",
            r"alerting",
            r"Alerting",
            r"dashboard",
            r"Dashboard",
            r"prometheus",
            r"grafana",
            r"datadog",
            r"newrelic",
            r"opentelemetry",
        ],
        negative_patterns=[],
    ),
    
    # MANAGE Function
    Requirement(
        id="nist-011",
        name="Risk Mitigation Controls",
        description="Implement controls to mitigate identified AI risks.",
        framework="NIST AI RMF",
        article="MANAGE-1",
        severity=Severity.CRITICAL,
        positive_patterns=[
            r"control",
            r"Control",
            r"mitigation",
            r"Mitigation",
            r"safeguard",
            r"Safeguard",
            r"countermeasure",
            r"Countermeasure",
            r"defense",
            r"Defense",
            r"protection",
            r"Protection",
            r"guardrail",
            r"Guardrail",
        ],
        negative_patterns=[],
    ),
    
    Requirement(
        id="nist-012",
        name="Incident Response & Recovery",
        description="Establish incident response procedures and recovery capabilities for AI system failures.",
        framework="NIST AI RMF",
        article="MANAGE-2",
        severity=Severity.HIGH,
        positive_patterns=[
            r"incident.?response",
            r"IncidentResponse",
            r"incident.?management",
            r"incident.?handling",
            r"recovery",
            r"Recovery",
            r"disaster.?recovery",
            r"business.?continuity",
            r"failover",
            r"Failover",
            r"rollback",
            r"Rollback",
            r"response.?plan",
            r"playbook",
        ],
        negative_patterns=[],
    ),
    
    Requirement(
        id="nist-013",
        name="Change Management",
        description="Manage changes to AI systems with proper versioning, testing, and approval processes.",
        framework="NIST AI RMF",
        article="MANAGE-3",
        severity=Severity.HIGH,
        positive_patterns=[
            r"change.?management",
            r"ChangeManagement",
            r"version.?control",
            r"VersionControl",
            r"git",
            r"Git",
            r"change.?approval",
            r"change.?review",
            r"deployment",
            r"Deployment",
            r"release.?management",
            r"ci.?cd",
            r"continuous.?integration",
            r"continuous.?deployment",
        ],
        negative_patterns=[],
    ),
    
    Requirement(
        id="nist-014",
        name="Transparency & Explainability",
        description="Provide transparency and explainability for AI system decisions and behavior.",
        framework="NIST AI RMF",
        article="MANAGE-4",
        severity=Severity.HIGH,
        positive_patterns=[
            r"transparency",
            r"Transparency",
            r"explainability",
            r"Explainability",
            r"explainable.?ai",
            r"XAI",
            r"interpretability",
            r"Interpretability",
            r"shap",
            r"SHAP",
            r"lime",
            r"LIME",
            r"feature.?importance",
            r"decision.?explanation",
            r"model.?card",
            r"ModelCard",
        ],
        negative_patterns=[],
    ),
]


def get_nist_ai_rmf_framework():
    """Return the NIST AI Risk Management Framework."""
    return {
        "name": "NIST AI RMF",
        "version": "1.0",
        "effective_date": "2023-01-26",
        "requirements": NIST_AI_RMF_REQUIREMENTS,
    }

